### ISSUE TITLE
How use the bot ?

### ISSUE THREAD

**Issue by ctoveloz** [spasticVerbalizer/tom-bot#28]
After installing the bot I tried to give the run command but got an error.
```
>sudo python setup.py
Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for tombot==0.2

>sudo tombot-run
Traceback (most recent call last):
  File "/usr/local/bin/tombot-run", line 9, in <module>
    load_entry_point('tombot==0.2', 'console_scripts', 'tombot-run')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/tombot-0.2-py2.7.egg/tombot/run.py", line 9, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ImportError: No module named apscheduler.schedulers.background
```
Thanks.

**Comment by spasticVerbalizer** [comment]
Because of a problem I had using setuptools dependencies need to be installed separately, using `sudo pip install -r requirements.txt` in the project's root directory.

Unfortunately, the bot requires some knowledge of yowsup, the library used to connect to Whatsapp, in order to be able to set it up. You first need to register your number using the instructions on [this page](https://github.com/tgalal/yowsup/wiki/yowsup-cli-2.0#yowsup-cli-registration) (note that it is impossible to use a number at the same time in Whatsapp on your phone and for the bot), to get the password needed to communicate with the Whatsapp servers.

Afterwards, you need to create a configuration file using `tombot-run -d > configuration.ini`, in which you can enter your yowsup phonenumber (do `ls ~/.yowsup` to see what to enter here) and your yowsup password, which you should have gotten while registering.

Once you've performed the above steps, you __should__ be able to run the bot using `tombot-run configuration.ini`, but it might also be the case that the bot fails because the setup process hasn't really been looked at or checked for quite some time. I'll probably go check it somewhere after the weekend, but I can't really promise anything as I'm currently in the middle of an exam week.

**Comment by mcabreb** [comment]
Did you finish your exam week?
